### ISSUE TITLE
Allowed Host Issue

### ISSUE THREAD

**Issue by abhishekp4** [ashishnyc/stuffpay#3]
Please fix this one as well. 
Request Method: | GET
-- | --
http://www.stuffpay.co.nz/
3.0.3
DisallowedHost
Invalid HTTP_HOST header: 'www.stuffpay.co.nz'. You may need to add 'www.stuffpay.co.nz' to ALLOWED_HOSTS.
/app/.heroku/python/lib/python3.6/site-packages/django/http/request.py in get_host, line 122
/app/.heroku/python/bin/python
3.6.11
['/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python36.zip',  '/app/.heroku/python/lib/python3.6',  '/app/.heroku/python/lib/python3.6/lib-dynload',  '/app/.heroku/python/lib/python3.6/site-packages']
Wed, 15 Jul 2020 23:13:08 +0000

**Comment by ashishnyc** [comment]
Added host in allowed host. 

Issue Fixed
